### PR TITLE
list->string fix null lists & add list? predicate

### PR DESCRIPTION
**Pull request by jitwit**
I noticed that `list->string` raised an error if passed `'()`. I considered changing the predicate to check for `pair?` or `null?` but thought it might make more sense to implement a proper `list?` procedure. `list?` uses tortoise-hair cycle detection to check for improper lists.

Also, is it reasonable to change `string=?` to use `eq?`? `string=?` was converting to lists of chars and calling `list-all-eq?`. I thought this change might be reasonable because of the current string representation and that `eq?` uses `===`. If no, what would a better way to replace `list-all-eq?` be?

### CODE REVIEW

**Comment by eholk** [comment]
Looks good to me!

Using `eq?` in `string=?` looks okay to me, since like you said, it's implemented with JavaScript's `===` under the hood. Although, I think this might mean we have a bug in `eq?` since `(eq? (list->string '(#\a #\b)) (list->string '(#\a #\b)))` should be `#f`, while `(string=? (list->string '(#\a #\b)) (list->string '(#\a #\b)))` should be `#t`.

To get the tests to pass, this needs a new snapshot. You can make one by doing `./mksnapshot.sh` and committing the results. Please do this as a commit by itself, so that it's easy to verify that the snapshot was generated exactly from the previously committed code. Or, I can make the snapshot for you.

**Comment by eholk** [comment]
Actually, maybe I'm wrong about the `eq?` thing. It depends on whether the runtime is comparing strings as objects or as strings, I guess. I opened #97 so we can add test coverage to make sure we have the right behavior and fix it if we don't.

**Comment by jitwit** [comment]
Currently, `(eq? (list->string '(#\a #\b)) (list->string '(#\a #\b)))` does return `#t`

**Comment by eholk** [comment]
Thanks for confirming! I guess that's something to follow up with on #97.

**Pull request merged**
