### PR TITLE
Explicit representation of nullary continuations

### PR DESCRIPTION
**Pull request by wingo**
This one is based on #60 (and thus #59 and #58).

Firstly I should apologize for a bit of the churn here.  My goal is to get to typed imports -- i.e. I should be able to declare an import as having type "i32 i32 -> void" and end up with efficient code.  This will also allow for anyref callouts, where the conversion between ref and i32 will have to be done in the runtime.  Thanks for bearing with me.

So, by default in the dialect of Scheme implemented by Schism, all expressions evaluate to a value.  Values that are in the head of a seq are implicitly dropped.  This PR changes to make this drop explicit, and as a corrolary to make the `head` of a `seq` node be a nullary continuation.

Explicitly representing the drop allows the compiler to be a bit smarter about how it deals with adapting between zero-valued and one-valued continuations.  In the future it will allow for efficient invocation of void-returning wasm imports.

In this patch, sadly, we have to distinguish between different types of "if".  This patch adds if/void for "if" nodes whose arms are nullary. Doing this allows us to simplify the compiler a bit.

We're back up to 1640 lines but down to 87869 bytes bootstrapped.  Bootstrap takes about 8-10% longer than master, with this patch.

### CODE REVIEW

**Comment by wingo** [comment]
Rebased on top of #60.

**Comment by eholk** [comment]
Huh, somehow there seem to be conflicts on `compiler.ss`. I'm not sure how though, since I just merged the PR you rebased this on top of.

**Comment by wingo** [comment]
I think the conflicts are because you rebased #60 instead of merging.  I just rebased to compensate.

**Comment by eholk** [comment]
That makes sense. It's a bummer Github can't figure things out through the rebase.

**Pull request merged**
